Appointments/urls.py
from django.urls import path
from Appointments import views
from Appointments.views import PatientCreate
from django.conf.urls import url

urlpatterns = [
    path('', PatientCreate.as_view(), name='home'),
    path('charge/', views.charge, name='charge'),
    path('ajax/load-cities/', views.load_time_slots, name='ajax_load_time_slots'),
    path('patient/', views.patient_view, name='p_view'),
    url(r'^new/(?P<start_time>\d{2}:\d{2}:\d{2})/(?P<day_date>\d{4}-\d{2}-\d{2})/$', views.create_event,name='new_event'),
    url(r'^appointment/(?P<pk>\d+)/$', views.appointment_detail, name='appointment-detail'),
]

Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Appointments.urls')),
]

Appointments/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.urls import reverse


class TimeSlots(models.Model):
    start = models.TimeField(null=True, blank=True)
    end = models.TimeField(null=True, blank=True)

    class Meta:
        ordering = ['start']

    def __str__(self):
        return '%s - %s' % (self.start.strftime("%I:%M %p"), self.end.strftime("%I:%M %p"))


class Event(models.Model):
    event_date = models.DateField()
    start = models.ForeignKey(TimeSlots, on_delete=models.CASCADE, verbose_name='Slot Time', null=True)
    available = models.BooleanField(default=True)

    class Meta:
        verbose_name = u'Event'
        verbose_name_plural = u'Event'

    def __str__(self):
        return str(self.event_date)

    def get_absolute_url(self):
        url = reverse('admin:%s_%s_change' % (self._meta.app_label, self._meta.model_name), args=[self.pk])
        return u'<a href="%s">%s</a>' % (url, str(self.start))


class Patient(models.Model):
    event_date = models.DateField(null=True)
    patient_ID = models.AutoField(primary_key=True)
    patient_name = models.CharField(max_length=60, null=True, blank=True)
    phone_number = PhoneNumberField(blank=True, null=True)
    email = models.EmailField()
    event = models.OneToOneField(Event, on_delete=models.CASCADE, null=True, blank=True)
    start = models.ForeignKey(TimeSlots, on_delete=models.CASCADE, null=True, verbose_name='Slot time')
    paid = models.BooleanField(default=False)
    skype_key = models.CharField(max_length=60, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('appointment-detail', args=[str(self.patient_ID)])

    def save(self, *args, **kwargs):
        self.event = Event.objects.get(event_date=self.event_date, start=self.start)
        change = Event.objects.get(pk=self.event.pk)
        change.available = False
        change.save()
        super(Patient, self).save(*args, **kwargs)

Appointments/forms.py
from django import forms
from .models import TimeSlots, Patient


class DateInput(forms.DateInput):
    input_type = 'date'


class PatientForm(forms.ModelForm):

    class Meta:
        model = Patient
        fields = ('patient_name','phone_number','email','event_date','start')
        widgets = {
            'event_date': DateInput(),
        }

    def __init__(self, *args, **kwargs):
        super(PatientForm, self).__init__(*args, **kwargs)
        self.fields['start'].queryset = TimeSlots.objects.none()

        if 'event_date' in self.data:
            try:
                event_id = self.data.get('event_date')
                # event = Event.objects.get(pk=event_id)
                self.fields['start'].queryset = TimeSlots.objects.filter(event__event_date=event_id, event__available=True)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['start'].queryset = self.instance.timeslot_set

Appointments/views.py
from .models import TimeSlots, Event, Patient
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render
from django.conf import settings
import stripe
from .forms import PatientForm
from django.views.generic import CreateView
from .send_mail import email_user
import datetime

stripe.api_key = settings.STRIPE_SECRET_KEY


def charge(request):  # new
    change = Patient.objects.create(
        event_date=request.POST.get('event_date'),
        patient_name=request.POST.get('patient_name'),
        phone_number=request.POST.get('phone_number'),
        email=request.POST.get('email'),
        start=TimeSlots.objects.filter(id=request.POST.get('start'))[0])
    change.save()
    if request.method == 'POST':
        charge = stripe.Charge.create(
            amount=5000,
            currency='usd',
            description='Book your appointment',
            source=request.POST['stripeToken']
        )
    change.paid = True
    change.save()
    email_user(change.email, change.patient_name, change.event_date, change.start)
    return render(request, 'charge.html')


class PatientCreate(CreateView):
    form_class = PatientForm
    template_name = 'index.html'

    def get_context_data(self, **kwargs):  # new
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


def load_time_slots(request):
    event_id = request.GET.get('event_date')
    time_slots = TimeSlots.objects.filter(event__event_date=event_id, event__available=True)
    return render(request, 'dropdown_list_options.html', {'time_slots': time_slots})


def create_event(request, start_time, day_date):
    time_slot = TimeSlots.objects.get(start=start_time)
    Event.objects.create(event_date=day_date, start=time_slot)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def patient_view(request):
    template_name = 'patient_dashboard.html'
    q = Patient.objects.filter(paid=True)
    context = {'q_list': q}
    return render(request, template_name, context)


def appointment_detail(request, pk):
    detail = Patient.objects.get(pk=pk)
    context = {
        'detail': detail,
    }
    return render(request, 'appointment_detail.html', context)

Appointments/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Django People</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">BOOK YOUR APPOINTMENT</h1>
          <hr class="mt-0 mb-4">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

Appointments/templates/charge.html
<h2>Thanks, you paid <strong>$50.00</strong>!</h2>

Appointments/templates/dropdown_list_options.html
<option value="">{% if time_slots %}Available Slots{% else %}No Slot Available{% endif %}</option>
{% for time_set in time_slots %}
<option value="{{ time_set.pk }}">{{ time_set.start }} - {{ time_set.end }}</option>
{% endfor %}

Appointments/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}
    {% load crispy_forms_tags %}
    {% block content %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>
<body>
<div align="right">
<a href="{% url 'p_view' %}">User Dashboard</a>
</div>

<form method="POST" action="{% url 'charge' %}" id="patientForm" data-times-url="{% url 'ajax_load_time_slots' %}">
  {% csrf_token %}
  {{ form.as_p }}
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="key"
              data-description="A Django Charge"
              data-amount="500"
              data-locale="auto"></script>
</form>


  <script>
    $("#id_event_date").change(function () {
      var url = $("#patientForm").attr("data-times-url");  // get the url of the `load_cities` view
      var eventId = $(this).val();  // get the selected country ID from the HTML input
      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'event_date': eventId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_start").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });
    });
  </script>
</body>
{% endblock %}
</html>

Appointments/templates/patient_dashboard.html
<center> <h1> User Dashboard</h1> </center>
{% if q_list %}
<ul>
{% for obj in q_list %}

    <h3>Name: {{obj.patient_name}}</h3>
Date: {{obj.event}}
<br>
Slot: {{obj.start}}
    <br>
         <a href="{{ obj.get_absolute_url }}">Go to details</a>
{% endfor %}
    {% endif %}
</ul>